spring.application.name=smart-campus

# NOTE:
# Do not hard-code DB credentials here. Use profile-specific files like
#   application-local.properties (H2)
#   application-prod.properties (MySQL)
# Datasource (Local H2)
spring.datasource.url=jdbc:h2:mem:smartcampusdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=708827420884-5tfs0leku4q51oc3gr5unia467r4uh28.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secret=smartcampus_secret_key_2024_sliit_very_long_key_256bits
jwt.expiration=86400000

server.port=8083

spring.main.allow-circular-references=true
