# Production profile (MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-16b60287-yasadapoorna-b1bb.c.aivencloud.com:11635/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:AVNS_BpF9QN3bXe-BIBIwkTI}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
