spring.datasource.url=jdbc:h2:mem:smartcampus-dev;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.security.oauth2.client.registration.google.client-id=dev-client-id
spring.security.oauth2.client.registration.google.client-secret=dev-client-secret
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secret=smartcampus_dev_secret_key_2024_sliit
jwt.expiration=86400000

server.port=8082
spring.main.allow-circular-references=true
