spring.application.name=smart-campus
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# NOTE:
# Do not hard-code DB credentials here. Use profile-specific files like
#   application-local.properties (H2)
#   application-prod.properties (MySQL)

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=708827420884-5tfs0leku4q51oc3gr5unia467r4uh28.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secret=smartcampus_secret_key_2024_sliit_very_long_key_256bits
jwt.expiration=86400000

server.port=8082

spring.main.allow-circular-references=true
